# Generated by Django 5.2.7 on 2026-01-19 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '积分标签',
                'verbose_name_plural': '积分标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='所有者ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='所有者类型')),
            ],
            options={
                'verbose_name': '积分钱包',
                'verbose_name_plural': '积分钱包',
            },
        ),
        migrations.CreateModel(
            name='PointSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('cash', '现金积分'), ('gift', '礼物积分')], db_index=True, max_length=10, verbose_name='积分类型')),
                ('original_amount', models.PositiveIntegerField(verbose_name='原始金额')),
                ('remaining_amount', models.PositiveIntegerField(verbose_name='剩余金额')),
                ('reason', models.CharField(max_length=200, verbose_name='发放原因')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='用于关联外部系统的ID', max_length=100, verbose_name='关联ID')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_sources', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='points.pointwallet', verbose_name='所属钱包')),
                ('tag', models.ForeignKey(blank=True, help_text='仅礼物积分可设置标签', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_sources', to='points.tag', verbose_name='积分标签')),
            ],
            options={
                'verbose_name': '积分来源',
                'verbose_name_plural': '积分来源',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', '获取'), ('spend', '消费'), ('withdraw', '提现'), ('expire', '过期')], db_index=True, max_length=10, verbose_name='交易类型')),
                ('point_type', models.CharField(choices=[('cash', '现金积分'), ('gift', '礼物积分')], max_length=10, verbose_name='积分类型')),
                ('amount', models.IntegerField(verbose_name='交易金额')),
                ('balance_after', models.PositiveIntegerField(verbose_name='交易后余额')),
                ('description', models.CharField(max_length=200, verbose_name='交易描述')),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='points.pointsource', verbose_name='积分来源')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='points.pointwallet', verbose_name='所属钱包')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='points.tag', verbose_name='积分标签')),
            ],
            options={
                'verbose_name': '积分交易',
                'verbose_name_plural': '积分交易',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='提现金额')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('bank_name', models.CharField(max_length=100, verbose_name='银行名称')),
                ('bank_account', models.CharField(max_length=50, verbose_name='银行账号')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='points.pointtransaction', verbose_name='关联交易')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='points.pointwallet', verbose_name='所属钱包')),
            ],
            options={
                'verbose_name': '提现申请',
                'verbose_name_plural': '提现申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pointwallet',
            index=models.Index(fields=['content_type', 'object_id'], name='points_poin_content_d09101_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointwallet',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='points_poin_wallet__fb7f26_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['wallet', 'point_type'], name='points_poin_wallet__7b4a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='pointtransaction',
            index=models.Index(fields=['created_at'], name='points_poin_created_e4144f_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsource',
            index=models.Index(fields=['wallet', 'point_type', 'remaining_amount'], name='points_poin_wallet__e9c576_idx'),
        ),
        migrations.AddIndex(
            model_name='pointsource',
            index=models.Index(fields=['expires_at'], name='points_poin_expires_d4bef5_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', 'created_at'], name='points_with_status_ed7592_idx'),
        ),
    ]
