# Generated by Django 5.2.7 on 2026-01-19 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_identifier', models.CharField(db_index=True, max_length=200, verbose_name='项目标识')),
                ('github_id', models.CharField(blank=True, max_length=50, verbose_name='GitHub ID')),
                ('github_login', models.CharField(db_index=True, max_length=100, verbose_name='GitHub 用户名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('start_month', models.DateField(verbose_name='起始月份')),
                ('end_month', models.DateField(verbose_name='结束月份')),
                ('contribution_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='贡献度')),
                ('raw_data', models.JSONField(default=dict, help_text='原始 OpenDigger 数据', verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贡献度缓存',
                'verbose_name_plural': '贡献度缓存',
            },
        ),
        migrations.CreateModel(
            name='PendingPointGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='GitHub ID')),
                ('github_login', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='GitHub 用户名')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='邮箱')),
                ('amount', models.PositiveIntegerField(verbose_name='积分金额')),
                ('point_type', models.CharField(choices=[('cash', '现金积分'), ('gift', '礼物积分')], max_length=10, verbose_name='积分类型')),
                ('reason', models.CharField(max_length=200, verbose_name='发放原因')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='关联ID')),
                ('granter_id', models.PositiveIntegerField(verbose_name='发放者ID')),
                ('is_claimed', models.BooleanField(db_index=True, default=False, verbose_name='已领取')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '待领取积分',
                'verbose_name_plural': '待领取积分',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiator_id', models.PositiveIntegerField(verbose_name='发起者ID')),
                ('total_amount', models.PositiveIntegerField(help_text='本次分配总额', verbose_name='本次分配总额')),
                ('project_scope', models.JSONField(help_text="项目筛选配置 {tags: [...], operation: 'AND'}", verbose_name='项目范围')),
                ('user_scope', models.JSONField(blank=True, help_text="用户筛选配置 {tags: [...], operation: 'AND'}", null=True, verbose_name='用户范围')),
                ('start_month', models.DateField(help_text='起始月份（月初）', verbose_name='起始月份')),
                ('end_month', models.DateField(help_text='结束月份（月初）', verbose_name='结束月份')),
                ('adjustment_ratio', models.DecimalField(decimal_places=2, default=1.0, help_text='全局调整比例', max_digits=5, verbose_name='全局调整比例')),
                ('individual_adjustments', models.JSONField(default=dict, help_text='单个用户调整 {user_id: amount}', verbose_name='单独调整')),
                ('contribution_data', models.JSONField(default=list, help_text='贡献度数据快照', verbose_name='贡献度数据')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('previewing', '预览中'), ('executing', '执行中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='总接收人数')),
                ('registered_recipients', models.PositiveIntegerField(default=0, verbose_name='已注册人数')),
                ('unregistered_recipients', models.PositiveIntegerField(default=0, verbose_name='未注册人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '积分分配',
                'verbose_name_plural': '积分分配',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='entity_identifier',
            field=models.CharField(blank=True, help_text='组织名称、仓库全名(owner/repo)或用户标识', max_length=200, verbose_name='实体标识'),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_official',
            field=models.BooleanField(db_index=True, default=True, help_text='是否为 OpenDigger 官方标签', verbose_name='官方标签'),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='所有者ID'),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner_type',
            field=models.ForeignKey(blank=True, help_text='私有标签的所有者类型', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_tags', to='contenttypes.contenttype', verbose_name='所有者类型'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_type',
            field=models.CharField(choices=[('general', '通用标签'), ('org', '组织标签'), ('repo', '仓库标签'), ('user', '用户标签')], db_index=True, default='general', max_length=20, verbose_name='标签类型'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['tag_type'], name='points_tag_tag_typ_3b93ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_official'], name='points_tag_is_offi_58acba_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['owner_type', 'owner_id'], name='points_tag_owner_t_671314_idx'),
        ),
        migrations.AddIndex(
            model_name='contributioncache',
            index=models.Index(fields=['project_identifier', 'start_month', 'end_month'], name='points_cont_project_96734f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contributioncache',
            unique_together={('project_identifier', 'github_login', 'start_month', 'end_month')},
        ),
        migrations.AddField(
            model_name='pendingpointgrant',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_pending_points', to=settings.AUTH_USER_MODEL, verbose_name='领取人'),
        ),
        migrations.AddField(
            model_name='pendingpointgrant',
            name='granter_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='发放者类型'),
        ),
        migrations.AddField(
            model_name='pendingpointgrant',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_grants', to='points.tag', verbose_name='积分标签'),
        ),
        migrations.AddField(
            model_name='pointallocation',
            name='initiator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='发起者类型'),
        ),
        migrations.AddField(
            model_name='pointallocation',
            name='source_pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='points.pointsource', verbose_name='积分池'),
        ),
        migrations.AddField(
            model_name='pendingpointgrant',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_grants', to='points.pointallocation', verbose_name='所属分配'),
        ),
        migrations.AddIndex(
            model_name='pointallocation',
            index=models.Index(fields=['status'], name='points_poin_status_b47c93_idx'),
        ),
        migrations.AddIndex(
            model_name='pointallocation',
            index=models.Index(fields=['initiator_type', 'initiator_id'], name='points_poin_initiat_c99493_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['is_claimed'], name='points_pend_is_clai_495809_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['github_id', 'is_claimed'], name='points_pend_github__29416f_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['github_login', 'is_claimed'], name='points_pend_github__d5a07c_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['email', 'is_claimed'], name='points_pend_email_69eb45_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['created_at'], name='points_pend_created_1cc513_idx'),
        ),
    ]
