# Generated by Django 5.2.7 on 2025-10-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='URL别名'),
        ),
    ]
