# Generated by Django 5.2.7 on 2026-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_contributioncache_pendingpointgrant_pointallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='id_card',
            field=models.CharField(default='', max_length=18, verbose_name='身份证号'),
        ),
    ]
