# Generated by Django 5.2.7 on 2025-10-05 16:34

from django.db import migrations
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    """为所有现有的 Tag 生成 slug."""
    Tag = apps.get_model("points", "Tag")
    for tag in Tag.objects.all():
        if not tag.slug:
            tag.slug = slugify(tag.name) or tag.name
            tag.save(update_fields=["slug"])


def reverse_populate_slug(apps, schema_editor):
    """反向操作：清空所有 slug."""
    Tag = apps.get_model("points", "Tag")
    Tag.objects.all().update(slug="")


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_add_slug_field'),
    ]

    operations = [
        migrations.RunPython(populate_slug, reverse_populate_slug),
    ]
