# Generated by Django 5.2.7 on 2026-01-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_withdrawalrequest_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='withdrawals/invoices/%Y/%m/', verbose_name='发票'),
        ),
    ]
