# Generated by Django 5.2.9 on 2026-05-17 04:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('points', '0004_withdrawalrequest_invoice_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. 先移除引用旧字段的联合索引
        migrations.RemoveIndex(
            model_name='pendingpointgrant',
            name='points_pend_github__29416f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pendingpointgrant',
            name='points_pend_github__d5a07c_idx',
        ),
        # 2. 使用 RenameField 保留数据
        migrations.RenameField(
            model_name='pendingpointgrant',
            old_name='github_id',
            new_name='actor_id',
        ),
        migrations.RenameField(
            model_name='pendingpointgrant',
            old_name='github_login',
            new_name='actor_login',
        ),
        # 3. 更新字段属性（verbose_name 等）
        migrations.AlterField(
            model_name='pendingpointgrant',
            name='actor_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='平台用户ID'),
        ),
        migrations.AlterField(
            model_name='pendingpointgrant',
            name='actor_login',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='平台用户名'),
        ),
        # 4. 添加 platform 新字段
        migrations.AddField(
            model_name='pendingpointgrant',
            name='platform',
            field=models.CharField(blank=True, db_index=True, default='github', max_length=50, verbose_name='平台'),
        ),
        # 5. 添加新的联合索引
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['actor_id', 'is_claimed'], name='points_pend_actor_i_a79311_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['actor_login', 'is_claimed'], name='points_pend_actor_l_5bab82_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpointgrant',
            index=models.Index(fields=['platform', 'actor_id'], name='idx_pending_platform_actor'),
        ),
    ]
