# Generated by Django 5.2.9 on 2026-05-22 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_withdrawal_account_model'),
        ('points', '0005_remove_pendingpointgrant_points_pend_github__29416f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='accounts.withdrawalaccount', verbose_name='提现账号'),
        ),
    ]
