# Generated by Django 5.2.9 on 2026-05-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_add_withdrawal_account_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('earn', '获取'), ('spend', '消费'), ('refund', '退回'), ('withdraw', '提现'), ('expire', '过期')], db_index=True, max_length=10, verbose_name='交易类型'),
        ),
    ]
