# Generated by Django 5.2.7 on 2025-10-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_alter_pointsource_user_alter_pointtransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='withdrawable',
            field=models.BooleanField(default=False, verbose_name='是否可提现'),
        ),
    ]
