# Generated by Django 5.2.7 on 2025-11-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0012_tag_allow_recharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('REJECTED', '已拒绝'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
