# Generated by Django 5.2.7 on 2025-11-04 01:48

from django.db import migrations


def create_default_tag(apps, schema_editor):
    """创建默认的 default 标签，支持充值和提现."""
    Tag = apps.get_model("points", "Tag")

    # 先尝试查找已存在的 default 标签（通过 slug 或 name）
    existing_tag = Tag.objects.filter(slug="default").first()
    if not existing_tag:
        existing_tag = Tag.objects.filter(name="默认").first()

    if existing_tag:
        # 如果标签已存在，更新其属性
        existing_tag.slug = "default"
        existing_tag.name = "默认"
        existing_tag.description = "用户默认积分池，支持充值和提现"
        existing_tag.is_default = True
        existing_tag.withdrawable = True
        existing_tag.allow_recharge = True
        existing_tag.save()
    else:
        # 如果标签不存在，创建新标签
        Tag.objects.create(
            slug="default",
            name="默认",
            description="用户默认积分池，支持充值和提现",
            is_default=True,
            withdrawable=True,
            allow_recharge=True,
        )


def reverse_default_tag(apps, schema_editor):
    """删除 default 标签."""
    Tag = apps.get_model("points", "Tag")
    Tag.objects.filter(slug="default").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_remove_approved_status'),
    ]

    operations = [
        migrations.RunPython(create_default_tag, reverse_default_tag),
    ]
