# Generated by Django 5.2.7 on 2025-12-18 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0014_create_default_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalContractSigning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待签署"),
                            ("SIGNED", "已签署"),
                            ("FAILED", "发起失败"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("real_name", models.CharField(max_length=100, verbose_name="真实姓名")),
                ("id_number", models.CharField(max_length=18, verbose_name="身份证号")),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="手机号"),
                ),
                ("bank_name", models.CharField(max_length=100, verbose_name="开户银行")),
                ("bank_account", models.CharField(max_length=50, verbose_name="银行账号")),
                (
                    "withdrawal_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用于签署完成后自动创建提现申请（例如 points / point_source_id）。",
                        verbose_name="提现申请信息",
                    ),
                ),
                (
                    "created_withdrawal_request_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="已创建的提现申请ID列表"
                    ),
                ),
                ("withdrawal_error", models.TextField(blank=True, verbose_name="提现创建错误")),
                (
                    "fdd_request_payload",
                    models.JSONField(blank=True, null=True, verbose_name="法大大请求"),
                ),
                (
                    "fdd_response_payload",
                    models.JSONField(blank=True, null=True, verbose_name="法大大响应"),
                ),
                (
                    "fdd_webhook_payload",
                    models.JSONField(blank=True, null=True, verbose_name="法大大回调"),
                ),
                (
                    "signed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="签署完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_contract_signings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "提现合同签署",
                "verbose_name_plural": "提现合同签署",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="withdrawalcontractsigning",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="PENDING"),
                fields=("user",),
                name="unique_pending_withdrawal_contract_per_user",
            ),
        ),
    ]
