# Generated by Django 5.2.7 on 2025-11-02 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='组织名称')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='组织描述')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像URL')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='网站')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('provider', models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitee', 'Gitee'), ('huggingface', 'HuggingFace'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=50, verbose_name='OAuth提供商')),
                ('provider_id', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='提供商组织ID')),
                ('provider_login', models.CharField(blank=True, max_length=200, verbose_name='提供商组织登录名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.organization', verbose_name='组织')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '组织成员',
                'verbose_name_plural': '组织成员',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='organizations', through='accounts.OrganizationMembership', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['user', 'role'], name='accounts_or_user_id_35d79a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'role'], name='accounts_or_organiz_eae39b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['provider', 'provider_id'], name='accounts_or_provide_00b03a_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='accounts_or_slug_7a4a7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('provider', 'provider_id')},
        ),
    ]
