# Generated by Django 5.2.7 on 2025-11-22 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("site_messages", "0001_initial"),
        ("accounts", "0010_remove_organization_avatar_url_organization_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_children",
                to=settings.AUTH_USER_MODEL,
                verbose_name="合并到",
            ),
        ),
        migrations.CreateModel(
            name="AccountMergeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_email_input", models.EmailField(blank=True, max_length=254, verbose_name="目标邮箱输入")),
                (
                    "target_username_input",
                    models.CharField(blank=True, max_length=150, verbose_name="目标用户名输入"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("ACCEPTED", "已同意"),
                            ("REJECTED", "已拒绝"),
                            ("EXPIRED", "已过期"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "approve_token",
                    models.CharField(
                        db_index=True, max_length=128, unique=True, verbose_name="确认令牌"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="处理时间")),
                ("asset_snapshot", models.JSONField(default=dict, verbose_name="资产快照")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_merge_requests",
                        to="site_messages.message",
                        verbose_name="关联消息",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_merge_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="处理人",
                    ),
                ),
                (
                    "source_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="源账号",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="目标账号",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号合并申请",
                "verbose_name_plural": "账号合并申请",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountMergeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("table_name", models.CharField(max_length=64, verbose_name="表名")),
                (
                    "migrated_count",
                    models.PositiveIntegerField(default=0, verbose_name="迁移数量"),
                ),
                (
                    "skipped_count",
                    models.PositiveIntegerField(default=0, verbose_name="跳过数量"),
                ),
                (
                    "conflict_count",
                    models.PositiveIntegerField(default=0, verbose_name="冲突数量"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="accounts.accountmergerequest",
                        verbose_name="合并请求",
                    ),
                ),
            ],
            options={
                "verbose_name": "账号合并日志",
                "verbose_name_plural": "账号合并日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountmergerequest",
            constraint=models.UniqueConstraint(
                condition=Q(status="PENDING"),
                fields=("source_user",),
                name="unique_pending_merge_per_source",
            ),
        ),
    ]
