# Generated by Django 5.2.7 on 2026-03-31 00:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_account_merge"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefreshToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jti",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="令牌ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True, verbose_name="过期时间")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="吊销时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refresh_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "刷新令牌",
                "verbose_name_plural": "刷新令牌",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="refreshtoken",
            index=models.Index(fields=["user", "created_at"], name="accounts_ref_user_id_e1c9e1_idx"),
        ),
    ]
