# Generated by Django 5.2.9 on 2026-04-27 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_email_ci_unique_non_empty'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='refreshtoken',
            new_name='accounts_re_user_id_5688ee_idx',
            old_name='accounts_ref_user_id_e1c9e1_idx',
        ),
    ]
