# Generated by Django 5.2.9 on 2026-05-22 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_ref_user_id_e1c9e1_idx_accounts_re_user_id_5688ee_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('domestic', '中国境内'), ('international', '中国以外')], max_length=20, verbose_name='账号类型')),
                ('real_name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_card', models.CharField(blank=True, default='', max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('bank_card', models.CharField(blank=True, default='', max_length=50, verbose_name='银行卡号')),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD')], default='', max_length=10, verbose_name='币种')),
                ('swift_account', models.CharField(blank=True, default='', max_length=100, verbose_name='SWIFT 账号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现账号',
                'verbose_name_plural': '提现账号',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'account_type'], name='accounts_wi_user_id_c9c671_idx')],
            },
        ),
    ]
