# Generated by Django 5.2.7 on 2025-10-18 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shippingaddress'),
        ('shop', '0002_shopitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='shipping_address',
            field=models.ForeignKey(blank=True, help_text='兑换时用户选择的收货地址（仅需要线下发货的商品）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='accounts.shippingaddress', verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='requires_shipping',
            field=models.BooleanField(default=False, help_text='如果选中，用户兑换时需要提供收货地址', verbose_name='需要线下发货'),
        ),
    ]
