# Generated by Django 5.2.7 on 2026-01-19 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
        ('shop', '0003_redemption_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='point_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption', to='points.pointtransaction', verbose_name='积分交易记录'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='allowed_tags',
            field=models.ManyToManyField(blank=True, help_text='如果为空，任何礼物积分都可兑换；否则只有指定标签的积分可用', related_name='shop_items', to='points.tag', verbose_name='允许的积分标签'),
        ),
    ]
