# Generated by Django 5.2.7 on 2026-01-19 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("points", "0001_initial"),
        ("shop", "0004_redemption_point_transaction_shopitem_allowed_tags"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="ShopItemAllowedTags",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "shopitem",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="shop.shopitem",
                            ),
                        ),
                        (
                            "tag",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="points.tag",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "shop_shopitem_allowed_tags",
                        "unique_together": {("shopitem", "tag")},
                    },
                ),
                migrations.AlterField(
                    model_name="shopitem",
                    name="allowed_tags",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="如果为空，任何礼物积分都可兑换；否则只有指定标签的积分可用",
                        related_name="shop_items",
                        through="shop.ShopItemAllowedTags",
                        to="points.tag",
                        verbose_name="允许的积分标签",
                    ),
                ),
            ],
        ),
    ]
