# Generated by Django 5.2.7 on 2026-02-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_shopitem_allowed_tags_through_model"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="redemption",
                    name="point_transaction",
                ),
            ],
        ),
    ]
