# Generated by Django 5.2.9 on 2026-06-24 05:13

import django.db.models.deletion
import shop.models
from django.db import migrations, models


def copy_old_fields_to_new(apps, schema_editor):
    """Copy name->name_zh, description->description_zh, image->image_card."""
    ShopItem = apps.get_model("shop", "ShopItem")
    for item in ShopItem.objects.all():
        item.name_zh = item.name or ""
        item.name_en = item.name or ""
        item.description_zh = item.description or ""
        if item.image:
            item.image_card = item.image
        item.save(
            update_fields=["name_zh", "name_en", "description_zh", "image_card"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_drop_user_email_unique"),
        ("shop", "0006_remove_redemption_point_transaction"),
    ]

    operations = [
        # Step 1: Add all new fields (with defaults for non-nullable ones)
        migrations.AddField(
            model_name="shopitem",
            name="name_zh",
            field=models.CharField(
                default="", max_length=100, verbose_name="商品名称(中文)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopitem",
            name="name_en",
            field=models.CharField(
                default="", max_length=100, verbose_name="商品名称(英文)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopitem",
            name="brief_zh",
            field=models.TextField(
                blank=True, default="", verbose_name="商品简介(中文)"
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="brief_en",
            field=models.TextField(
                blank=True, default="", verbose_name="商品简介(英文)"
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="description_zh",
            field=models.TextField(default="", verbose_name="商品描述(中文)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shopitem",
            name="description_en",
            field=models.TextField(
                blank=True, default="", verbose_name="商品描述(英文)"
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="image_card",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=shop.models.shop_item_card_path,
                verbose_name="首页卡片图",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="image_detail",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=shop.models.shop_item_detail_path,
                verbose_name="详情页大图",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="message_title_template_zh",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="站内信标题模板(中文)",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="message_title_template_en",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="站内信标题模板(英文)",
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="message_content_template_zh",
            field=models.TextField(
                blank=True, default="", verbose_name="站内信内容模板(中文)"
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="message_content_template_en",
            field=models.TextField(
                blank=True, default="", verbose_name="站内信内容模板(英文)"
            ),
        ),
        migrations.AddField(
            model_name="shopitem",
            name="coupon_type",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="关联兑换码类型"
            ),
        ),
        # Step 2: Copy data from old fields to new fields
        migrations.RunPython(
            copy_old_fields_to_new,
            reverse_code=migrations.RunPython.noop,
        ),
        # Step 3: Remove old fields
        migrations.RemoveField(
            model_name="shopitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="shopitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="shopitem",
            name="image",
        ),
        # Step 4: Create CouponCode model
        migrations.CreateModel(
            name="CouponCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="兑换码类型"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=500, verbose_name="兑换码"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "可用"),
                            ("used", "已使用"),
                            ("disabled", "已禁用"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="兑换时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                        verbose_name="兑换用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "兑换码",
                "verbose_name_plural": "兑换码",
                "indexes": [
                    models.Index(
                        fields=["code_type", "status"],
                        name="shop_coupon_code_ty_f08a6d_idx",
                    )
                ],
                "unique_together": {("code_type", "code")},
            },
        ),
    ]
