# Generated by Django 5.2.9 on 2026-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shopitem_description_remove_shopitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='coupon_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='关联兑换码类型'),
        ),
    ]
