# Generated by Django 5.2.9 on 2026-08-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_coupon_type_remove_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='point_tag_slug',
            field=models.CharField(blank=True, help_text='兑换时使用的特定标签积分（仅 gift 类型）', max_length=50, null=True, verbose_name='支付积分标签slug'),
        ),
        migrations.AddField(
            model_name='redemption',
            name='point_type',
            field=models.CharField(choices=[('cash', '现金积分'), ('gift', '礼物积分')], default='gift', max_length=10, verbose_name='支付积分类型'),
        ),
    ]
