# Generated by Django 5.2.9 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_redemption_point_tag_slug_redemption_point_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopitem",
            name="priority",
            field=models.IntegerField(
                default=1,
                help_text="数值越大，商城展示越靠前；售罄商品始终排在有库存商品之后",
                verbose_name="优先级",
            ),
        ),
    ]
