"""Add redemption payment breakdowns and clarify shop item tag behavior."""

# Generated by Django 5.2.9 on 2026-08-25 11:06

import django.db.models.deletion
from django.db import migrations, models


def backfill_redemption_payment_lines(apps, schema_editor):
    """Represent historical single-pool redemptions with one payment line."""
    Redemption = apps.get_model("shop", "Redemption")
    RedemptionPaymentLine = apps.get_model("shop", "RedemptionPaymentLine")
    lines = []
    for redemption in Redemption.objects.all().iterator(chunk_size=1000):
        lines.append(
            RedemptionPaymentLine(
                redemption_id=redemption.id,
                point_type=redemption.point_type,
                tag_slug=(
                    redemption.point_tag_slug
                    if redemption.point_type == "gift"
                    else None
                ),
                amount=redemption.points_cost_at_redemption,
            )
        )
        if len(lines) == 1000:
            RedemptionPaymentLine.objects.bulk_create(lines)
            lines = []
    if lines:
        RedemptionPaymentLine.objects.bulk_create(lines)


def remove_backfilled_payment_lines(apps, schema_editor):
    """Delete payment lines before reversing the schema migration."""
    RedemptionPaymentLine = apps.get_model("shop", "RedemptionPaymentLine")
    RedemptionPaymentLine.objects.all().delete()


class Migration(migrations.Migration):
    """Create and backfill redemption payment lines."""

    dependencies = [
        ("shop", "0010_shopitem_priority"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedemptionPaymentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[("cash", "现金积分"), ("gift", "礼物积分")],
                        max_length=10,
                        verbose_name="积分类型",
                    ),
                ),
                (
                    "tag_slug",
                    models.CharField(
                        blank=True,
                        help_text="支付时的标签快照；无标签礼物积分和现金积分为空",
                        max_length=50,
                        null=True,
                        verbose_name="积分标签 slug",
                    ),
                ),
                ("amount", models.PositiveIntegerField(verbose_name="支付积分")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "redemption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_lines",
                        to="shop.redemption",
                        verbose_name="兑换记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "兑换支付明细",
                "verbose_name_plural": "兑换支付明细",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="shopitem",
            name="allowed_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="带标签礼物积分必须匹配此处标签；通用礼物积分和现金积分始终可用",
                related_name="shop_items",
                through="shop.ShopItemAllowedTags",
                to="points.tag",
                verbose_name="允许的积分标签",
            ),
        ),
        migrations.RunPython(
            backfill_redemption_payment_lines,
            reverse_code=remove_backfilled_payment_lines,
        ),
    ]
