# Generated by Django 5.2.9 on 2026-09-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_redemptionpaymentline'),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopitem",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="关闭后，中国站和国际站都不会展示或允许兑换该商品",
                verbose_name="全站上架总开关",
            ),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_listed_on_cn',
            field=models.BooleanField(default=True, help_text='在 open-share.cn 的商城中展示并允许兑换', verbose_name='中国站上架'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_listed_on_global',
            field=models.BooleanField(default=True, help_text='在 open-share.com 的商城中展示并允许兑换', verbose_name='国际站上架'),
        ),
    ]
