# Generated by Django 5.2.9 on 2026-06-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('site_messages', '0002_alter_message_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tag_ids', models.JSONField(default=list)),
                ('tag_names', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('countries', models.JSONField(default=list)),
                ('regions', models.JSONField(default=list)),
                ('top_n', models.PositiveIntegerField(blank=True, null=True)),
                ('point_type', models.CharField(max_length=10)),
                ('cost_per_user', models.PositiveIntegerField()),
                ('total_cost', models.PositiveIntegerField()),
                ('reward_ratio', models.FloatField()),
                ('reward_pool', models.PositiveIntegerField()),
                ('reward_expiry_days', models.PositiveIntegerField()),
                ('total_recipients', models.PositiveIntegerField()),
                ('delivered_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('rewarded_count', models.PositiveIntegerField(default=0)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='sending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_campaigns', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_messages.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='OutreachRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.PositiveIntegerField()),
                ('openrank_score', models.FloatField(default=0)),
                ('is_rewarded', models.BooleanField(default=False)),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('reward_expired', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_records', to='talent_reach.outreachcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_messages.usermessage')),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
    ]
