# Generated by Django 5.2.9 on 2026-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='content_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='title_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='outreachdraft',
            name='content_zh',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='outreachdraft',
            name='title_zh',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
