# Generated by Django 5.2.9 on 2026-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent_reach', '0003_outreachcampaign_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreachcampaign',
            name='source_owner_slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='source_owner_type',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='outreachcampaign',
            name='tag_slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
