# Generated by Django 5.2.7 on 2025-12-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='英文名称')),
                ('name_zh', models.CharField(max_length=200, verbose_name='中文名称')),
                ('type', models.CharField(choices=[('project', '项目'), ('enterprise', '企业'), ('foundation', '基金会'), ('technology', '技术领域'), ('community', '社区')], db_index=True, max_length=20, verbose_name='标签类型')),
                ('owner_type', models.CharField(choices=[('system', '系统'), ('user', '个人'), ('organization', '组织')], db_index=True, default='user', max_length=20, verbose_name='所有者类型')),
                ('owner_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='所有者ID')),
                ('data', models.JSONField(default=dict, verbose_name='标签数据')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('sync_source', models.CharField(blank=True, max_length=50, null=True, verbose_name='同步来源')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'labels',
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='labels_owner_t_09f378_idx'), models.Index(fields=['type', 'is_public'], name='labels_type_c20be6_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'owner_type', 'owner_id'), name='unique_label_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='LabelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grantee_type', models.CharField(choices=[('user', '用户'), ('organization', '组织')], max_length=20, verbose_name='被授权对象类型')),
                ('grantee_id', models.IntegerField(verbose_name='被授权对象ID')),
                ('permission_level', models.CharField(choices=[('view', '查看'), ('use', '使用'), ('edit', '编辑'), ('manage', '管理')], max_length=20, verbose_name='权限级别')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权者')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='labels.label', verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签权限',
                'verbose_name_plural': '标签权限',
                'db_table': 'label_permissions',
            },
        ),
        migrations.CreateModel(
            name='LabelPermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', '授予'), ('updated', '更新'), ('revoked', '撤销'), ('expired', '过期')], max_length=20, verbose_name='操作')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('details', models.JSONField(default=dict, verbose_name='变更详情')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labels.labelpermission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '标签权限日志',
                'verbose_name_plural': '标签权限日志',
                'db_table': 'label_permission_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='labelpermission',
            index=models.Index(fields=['label', 'grantee_type', 'grantee_id'], name='label_permi_label_i_450297_idx'),
        ),
        migrations.AddIndex(
            model_name='labelpermission',
            index=models.Index(fields=['grantee_type', 'grantee_id', 'is_active'], name='label_permi_grantee_dc3eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='labelpermission',
            index=models.Index(fields=['expires_at'], name='label_permi_expires_686383_idx'),
        ),
        migrations.AddConstraint(
            model_name='labelpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('label', 'grantee_type', 'grantee_id'), name='unique_active_permission'),
        ),
    ]
