# Generated by Django 5.2.7 on 2025-12-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='sync_source',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='同步来源'),
        ),
    ]
