# Generated by Django 5.2.9 on 2026-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='签约 ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='姓名')),
                ('mobile', models.CharField(db_index=True, max_length=20, verbose_name='手机号')),
                ('id_card', models.CharField(db_index=True, max_length=32, verbose_name='身份证号')),
                ('provider_id', models.BigIntegerField(verbose_name='服务商 ID')),
                ('payment_type', models.IntegerField(default=0, verbose_name='结算方式')),
                ('state', models.IntegerField(db_index=True, default=1, verbose_name='签约状态')),
                ('force_create_contract_flag', models.BooleanField(default=False, verbose_name='强制创建合同标记')),
                ('ret_msg', models.CharField(blank=True, default='', max_length=255, verbose_name='返回信息')),
                ('raw_data', models.JSONField(default=dict, verbose_name='原始返回数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='入库时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '身边云签约用户',
                'verbose_name_plural': '身边云签约用户',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_card', 'mobile', 'name'], name='sby_signed_identity_idx')],
            },
        ),
    ]
