# Generated by Django 5.2.9 on 2026-05-22 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_add_withdrawal_account_fk'),
        ('shenbianyun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mer_batch_id', models.CharField(db_index=True, max_length=32, verbose_name='商户批次号')),
                ('mer_order_id', models.CharField(max_length=32, unique=True, verbose_name='商户订单号')),
                ('order_no', models.CharField(blank=True, default='', max_length=25, verbose_name='平台订单号')),
                ('amount', models.PositiveIntegerField(verbose_name='付款金额（分）')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='服务费（分）')),
                ('user_fee', models.PositiveIntegerField(default=0, verbose_name='个人服务费/个税（分）')),
                ('user_due_amt', models.PositiveIntegerField(default=0, verbose_name='个人实际到账（分）')),
                ('state', models.IntegerField(choices=[(0, '已发起'), (1, '付款中'), (3, '成功'), (4, '失败'), (6, '待用户确认'), (7, '已取消')], default=0, verbose_name='付款状态')),
                ('res_msg', models.TextField(blank=True, default='', verbose_name='响应信息')),
                ('payee_name', models.CharField(max_length=50, verbose_name='收款人姓名')),
                ('payee_acc', models.CharField(max_length=28, verbose_name='收款人账号')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('payment_type', models.IntegerField(default=0, verbose_name='付款方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='交易完成时间')),
                ('withdrawal_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='points.withdrawalrequest', verbose_name='提现申请')),
            ],
            options={
                'verbose_name': '付款记录',
                'verbose_name_plural': '付款记录',
                'indexes': [models.Index(fields=['mer_batch_id', 'order_no'], name='shenbianyun_mer_bat_76cc34_idx'), models.Index(fields=['state'], name='shenbianyun_state_0a06ce_idx')],
            },
        ),
    ]
