# Generated by Django 5.2.9 on 2026-06-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('system', '系统消息'), ('personal', '个人消息'), ('payment', '支付信息'), ('shipping', '发货信息'), ('activity', '活动通知'), ('announcement', '公告'), ('points', '积分变动'), ('order', '订单信息'), ('security', '安全提醒'), ('withdrawal', '提现信息'), ('outreach', 'Outreach')], default='system', max_length=20, verbose_name='消息类型'),
        ),
    ]
